/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vehcilesystem.view;

/**
 *
 * @author user
 */
public class Dashboard_Page extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_Page
     */
    public Dashboard_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DasBackgrnd = new javax.swing.JPanel();
        RegNo = new javax.swing.JButton();
        CustomerPage = new javax.swing.JButton();
        RentalPage = new javax.swing.JButton();
        ReturnPage = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DasBackgrnd.setBackground(new java.awt.Color(0, 102, 102));
        DasBackgrnd.setPreferredSize(new java.awt.Dimension(800, 500));
        DasBackgrnd.setLayout(null);

        RegNo.setBackground(new java.awt.Color(0, 102, 102));
        RegNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegNo.setForeground(new java.awt.Color(204, 204, 204));
        RegNo.setText("Vechile Registration");
        RegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegNoActionPerformed(evt);
            }
        });
        DasBackgrnd.add(RegNo);
        RegNo.setBounds(310, 120, 190, 40);

        CustomerPage.setBackground(new java.awt.Color(0, 102, 102));
        CustomerPage.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        CustomerPage.setForeground(new java.awt.Color(204, 204, 204));
        CustomerPage.setText("Customer");
        CustomerPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerPageActionPerformed(evt);
            }
        });
        DasBackgrnd.add(CustomerPage);
        CustomerPage.setBounds(310, 180, 190, 40);

        RentalPage.setBackground(new java.awt.Color(0, 102, 102));
        RentalPage.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        RentalPage.setForeground(new java.awt.Color(204, 204, 204));
        RentalPage.setText("Rental");
        RentalPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentalPageActionPerformed(evt);
            }
        });
        DasBackgrnd.add(RentalPage);
        RentalPage.setBounds(310, 240, 190, 40);

        ReturnPage.setBackground(new java.awt.Color(0, 102, 102));
        ReturnPage.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ReturnPage.setForeground(new java.awt.Color(204, 204, 204));
        ReturnPage.setText("Return");
        ReturnPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnPageActionPerformed(evt);
            }
        });
        DasBackgrnd.add(ReturnPage);
        ReturnPage.setBounds(310, 300, 190, 40);

        LogOut.setBackground(new java.awt.Color(0, 102, 102));
        LogOut.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LogOut.setForeground(new java.awt.Color(204, 204, 204));
        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        DasBackgrnd.add(LogOut);
        LogOut.setBounds(310, 360, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DasBackgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DasBackgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RentalPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentalPageActionPerformed
        // TODO add your handling code here:
        RentalPage rp = new RentalPage();
        rp.setVisible(true);
        rp.pack();
        rp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_RentalPageActionPerformed

    private void CustomerPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerPageActionPerformed
        // TODO add your handling code here:
        Customer_Page cp = new Customer_Page();
        cp.setVisible(true);
        cp.pack();
        cp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_CustomerPageActionPerformed

    private void ReturnPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnPageActionPerformed
        // TODO add your handling code here:
        ReturnPage RP = new ReturnPage();
        RP.setVisible(true);
        RP.pack();
        RP.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ReturnPageActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        Login_Page log = new Login_Page();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void RegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegNoActionPerformed
        // TODO add your handling code here:
        Vehicle_Registration v = new Vehicle_Registration();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomerPage;
    private javax.swing.JPanel DasBackgrnd;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton RegNo;
    private javax.swing.JButton RentalPage;
    private javax.swing.JButton ReturnPage;
    // End of variables declaration//GEN-END:variables
}
