/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vehcilesystem.view;

/**
 *
 * @author user
 */
public class Dashboard_Page extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_Page
     */
    public Dashboard_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DasBackgrnd = new javax.swing.JPanel();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        BckImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DasBackgrnd.setBackground(new java.awt.Color(33, 114, 75));
        DasBackgrnd.setPreferredSize(new java.awt.Dimension(800, 500));
        DasBackgrnd.setLayout(null);

        Btn1.setBackground(new java.awt.Color(0, 0, 0,80));
        Btn1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Btn1.setForeground(new java.awt.Color(255, 255, 255));
        Btn1.setText("Vehilcle Registration");
        Btn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        DasBackgrnd.add(Btn1);
        Btn1.setBounds(300, 110, 191, 30);

        Btn2.setBackground(new java.awt.Color(0, 0, 0,80));
        Btn2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Btn2.setForeground(new java.awt.Color(255, 255, 255));
        Btn2.setText("Customer Registration");
        Btn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });
        DasBackgrnd.add(Btn2);
        Btn2.setBounds(300, 170, 191, 35);

        Btn3.setBackground(new java.awt.Color(0, 0, 0,80));
        Btn3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Btn3.setForeground(new java.awt.Color(255, 255, 255));
        Btn3.setText("Rental Info");
        Btn3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        DasBackgrnd.add(Btn3);
        Btn3.setBounds(300, 230, 191, 35);

        Btn4.setBackground(new java.awt.Color(0, 0, 0,80));
        Btn4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Btn4.setForeground(new java.awt.Color(255, 255, 255));
        Btn4.setText("Return");
        Btn4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        DasBackgrnd.add(Btn4);
        Btn4.setBounds(300, 300, 191, 35);

        Btn5.setBackground(new java.awt.Color(0, 0, 0,40));
        Btn5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Btn5.setForeground(new java.awt.Color(255, 255, 255));
        Btn5.setText("Log Out");
        Btn5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        DasBackgrnd.add(Btn5);
        Btn5.setBounds(300, 370, 191, 35);

        BckImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\91601.jpg")); // NOI18N
        DasBackgrnd.add(BckImg);
        BckImg.setBounds(0, -30, 800, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DasBackgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DasBackgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BckImg;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JPanel DasBackgrnd;
    // End of variables declaration//GEN-END:variables
}
